### ISSUE TITLE
Use CSS

### ISSUE THREAD

**Issue by qx12345678** [qx12345678/fa22-cse110-lab3#1]
# TASK
- [x] Access to CSS

CSS Topic:
- [x] comment

- color
- [x] rgb/rgba
- [x] #FFF/#FFFFFF
- [x] hsl/hsla
- [x] Color Name

- Background
- [x] background-color

- Unit

- [x] 3 unique relative units total

- [x] 3 unique absolute units total

- Box Model
- [x] Margin
- [x] padding
- [x] Borders

- Text

- [x] color
- [x] text-decoration
- [x] text-align

**Comment by qx12345678** [comment]
finished
